
# All the Nether Roof stuff permission node is roof.use
Nether_Tp: true
Tp_Complete_Message: "&b[prefix] &dYou have been teleported to the nether roof!"
Wrong_Y_Message: "&b[prefix] &dYou must be at Y level 125 to execute this command!"
Wrong_World_Message: "&b[prefix] &dYou have to be in the nether to get on the nether roof silly!"

# Insufficient permissions.
Insufficient_Permissions_Message: "&4You do not have permissions to execute this command! Contact your admin!"

# All the join messages
FirstJoin: "&b<player> &dhas joined for the first time!"
Join: "&b<player> &dhas joined the game!"
Leave: "&b<player> &dhas left the game!"

# Wither stuff
Disable_Withers: true

# Possible Thunder Hack Patch
ThunderHackPatch: true

# Flirt Stuff. permission node flirt.use
Flirt: "&b[VILE] &dHey baby, you look mighty fine today~ ;3"
Finish_Flirt: "&bSent a flirt to &d<player>"

# Discord link. permission node discord.use
Discord_Link: "&bJoin today! &dhttps://discord.gg/UJgdqV93SU"

# Enables a tps command using /ticks because my dumb ass can't figure out why /tps still is showing the default one.
tps: true

# Enables an op dupe, by default it is off, but if you like the salc1 dupe, turn it on.
Enable_Dupe: false

# Help thing.
Help:
  - "&b[---------------------HELP---------------------]"
  - "&d/vote - Vote for the server to unlock commands"
  - "&d/w - whisper command"
  - "&d/r - reply command"
  - "&d/ignore - ignore all messages from a player also let's you un-ignore."
  - "&d/stats - shows server stats"
  - "&d/tpa -  tpa if you vote."
  - "&d/tpy <player> - accepts tpa"
  - "&d/tpn <player> - denies tpa"
  - "&d/jd - shows join date"
  - "&d/nc - shows name color"
  - "&d/flirt - flirts at you"
  - "&d/hat - puts block on your head"
  - "&b[---------------------HELP---------------------]"