name: Core
version: ${project.version}
main: me.krymz0n.core.Main
authors: [ KRYMZ0N ]
description: A core plugin for my server 3b3t.me. Feel free to use, but it is intended for my server.
website: http://www.16b16t.net/

commands:
  discord:
    description: yes
  flirt:
    description: yes
  help:
    description: yes
  kill:
    description: yes
  roof:
    description: yes
  ticks:
    description: yes
    aliases: [tps]
  3b3t:
    description: yes
  coords:
    description: yes